### ISSUE TITLE
Steps missing for deploying?

### ISSUE THREAD

**Issue by wezter96** [chamatt/create-kaol-app#4]
Hi! :)
I've tried to use this template but when deploying to Vercel I first get issues with env variables for Prisma.
![image](https://user-images.githubusercontent.com/23472050/190388923-6aac8b0c-fb4f-496c-a5d0-6319f3cf74e9.png)

if I push my env variables to the repository as well as Vercel I manage to get it deployed but none of my paths are working.

I enabled directory listing but I'm relatively new to Next.js (only tried it a bit through Solito) so it didn't make me much wiser.
https://gig-hub.vercel.app/

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/23472050/190389066-e8d262ba-7c7f-4f77-bd92-d1ab347c1957.png">

Are there some steps missing on how I should get this template deployded?
I'm looking to move my Solito project to this template but sadly I'm a bit stuck.

**Comment by chamatt** [comment]
Hi @wezter96. Maybe there's some step missing. Can you check on your vercel config and see if the next.js entry point is configured as follows? 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/20344348/191385141-e285db1a-bead-4a6d-9989-ae780ca5a3d9.png">

**Comment by wezter96** [comment]
I even deleted the local .env file and I still get the same error.
Is there anything I need to change in Build & Development Settings?
Should I have it marked as Production, Preview and Development even though it says only to have it marked as Production?
Sorry it took a while for me to respond, I injured my hands 1.5 weeks ago so I haven't been programming as much.
I have the env variables configured in Vercel but somehow Prisma does not seem to find the env if I am not missing something?

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/23472050/193428238-f3cb53ba-b5ca-4f42-8a30-fe1376fc4003.png">
<img width="290" alt="image" src="https://user-images.githubusercontent.com/23472050/193428273-ab26a294-b82f-4133-b15c-c944df10edfe.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/23472050/193428408-2f9c2974-e8df-459c-ad65-588137639dc7.png">

**Comment by wezter96** [comment]
@chamatt Do you think this might be the issue in the repo it says to add a MIGRATION_DB_URL env variable in vercel but in the script in the package json file it says MIGRATE_DB_URL?
"vercel-build": "DATABASE_URL=$MIGRATE_DB_URL prisma generate && DATABASE_URL=$MIGRATE_DB_URL prisma migrate deploy && next build"

<img width="983" alt="image" src="https://user-images.githubusercontent.com/23472050/194672003-afb0ce7c-60b7-4017-8261-8d45c4d3737f.png">

**Comment by chamatt** [comment]
@wezter96 Yep, that's most probably it. I just fixed this on the readme. Thank you for pointing this out
