### ISSUE TITLE
NativeWind instead of twrnc ?

### ISSUE THREAD

**Issue by redbar0n** [chamatt/create-kaol-app#6]
Would you consider using NativeWind instead of twrnc for this repo?

twrnc aka. [tailwind-react-native-classnames](https://github.com/jaredh159/tailwind-react-native-classnames) does its work during runtime, and since it has its own interpreter the repo would need to be maintained in sync with compiler updates in new Tailwind releases.

NativeWind just uses the Tailwind compiler itself, so is automatically in syc. It also supports the [crucial](https://dev.to/redbar0n/how-to-combine-react-native-web-responsivity-nextjs-ssr-to-get-seo-a4g) feature: _responsive CSS media queries during SSR_.

Further [comparison of twrnnc vs. NativeWind](https://github.com/jaredh159/tailwind-react-native-classnames/discussions/171#discussioncomment-3097079), by the NativeWind creator.

**Comment by chamatt** [comment]
That's what I tried at first, but had a lot of problems getting it to work properly on both web and mobile :(

**Comment by chamatt** [comment]
Closed as I don't plan on working on this in the near future. But feel free to open a PR with this!
